corpora:
  # Paths for the location of files relevant to each corpus.
  #
  # Each corpus has a path and an index.
  #
  #   path: the absolute location of the .corpus file
  #   index: the absolute location of the .freqdist file

  bnc:
    path:  "/Volumes/Data/corpora/BBC/2 Tokenised/BNC.corpus"
    index: "/Volumes/Data/indices/BNC.freqdist"

  subtitles:
    path:  "/Volumes/Data/corpora/BBC/4 Tokenised/BBC.corpus"
    index: "/Volumes/Data/indexes/BBC.freqdist"

  ukwac:
    path:  "/Volumes/Data/corpora/BBC/3 Tokenised/UKWAC.corpus"
    index: "/Volumes/Data/indices/UKWAC.freqdist"

models:
  # The directory where all models live.  Within this directory, models must be arranged in the following manner:
  #
  #   <directory>/<model-name>/<*model-files>
  directory: "/Volumes/Data/vectors"
